### ISSUE TITLE
Have problem with "make adb/adbd"

### ISSUE THREAD

**Issue by wujingbang** [hadess/adbd#1]
Hi, is there a tutorial for build an non-android adbd? 
I have run the "make adb/adbd" and got problem like "adb_listeners.cpp:29:5: error: expected primary-expression before ‘.’ token; adb_listeners.cpp:30:5: error: expected primary-expression before ‘.’ token" .
Many thanks!

**Comment by hadess** [comment]
"make" is sufficient to build the adbd in this repositorym and I can't reproduce your error.
If you want to get adbd running on your non-android system, you're on your own though.
