### ISSUE TITLE
Problem on detecting the UDC driver

### ISSUE THREAD

**Issue by dayburak** [hadess/adbd#5]
Hello,

My environment is Ubuntu 16.0.4 and I have problems with detecting the correct UDC driver. I have tried all the modules under /kernel/drivers/usb/gadget/udc but still having no sight of any driver under /sys/class/udc. So xdg-adbd stucks on enabling UDC since no driver is defined in the source code.

Can you guide me through deciding the correct udc driver to use?
Thanks.

**Comment by hadess** [comment]
What device is it? Are you sure it can actually use this?

**Comment by dayburak** [comment]
I'm trying to use adbd between two laptops having ubuntu 16.0.4 with a to a cable. If you are asking device chipset or usb specific information I need to check first

**Comment by hadess** [comment]
This won't work with laptops, sorry.

**Comment by dayburak** [comment]
Which device or os is supposed to run this build may I ask? Thank you so far for your answers

**Comment by hadess** [comment]
Linux, and devices with UDC drivers (CHIP, phone, tablet). Laptops and Windows tablets usually don't have UDC drivers...

**Comment by dayburak** [comment]
So lastly, could you suggest any udc driver for laptop or any work around solution. And btw, connection over tcp ip with adb connect just works fine, nothing wrong with the build great work. The only problem is suitable udc driver

**Comment by hadess** [comment]
You can't have a UDC driver if there's no OTG capable hardware in your device. You need to find a device that does. Devices that usually run Android usually have that, tablets that usually run Windows usually don't.
