### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by GithubRyze** [hadess/adbd#7]
build failed ,./include/cutils/jstring.h:24:19: fatal error: uchar.h: No such file or directory.  did i build wrong?
i want run adbd in linux which kenerl is 3.9 and make tool is arm-linux-gcc. can you help me??
thank you !!

**Comment by hadess** [comment]
It's part of the glibc headers. You need that installed. I doubt this repo is the one you're looking for to be honest...

**Comment by GithubRyze** [comment]
Hi friend:
    i am a newer for linux.  my PM want transfer camera data in linux to windows by USB. and we linux not support UVC.
At first we try use RNDIS. But windows driver always installed failed. so we want transfer by usb like android adb.  so i found this repo in git.
do you have any suggestions for me? and can we make it success by adbd?
  I really appreciate you can response me!!!
thanks!!

**Comment by hadess** [comment]
Try looking into PTP support in the kernel. This is way off topic for this bug, and adbd is a developer tool, nothing that should be relied on for data transfers initiated by users.
